name: Lint & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.18'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Test
        run: go test -v ./...
